### ISSUE TITLE
Inventory looks wierd when using Dark Mode pack

### ISSUE THREAD

**Issue by Rafii2198** [Compliance-Resource-Pack/Compliance-Bedrock-32x#1]
This is how it looks with Dark Mode pack. This does not happen with any other resolution packs like **Classic Faithful x32** for example. Only the item bar looks normal from what I found
![obraz](https://user-images.githubusercontent.com/26695327/155400744-e6e04255-a0f2-439e-b555-a21f9b0e7c8c.png)
These are my packs _(last one is default)_
![obraz](https://user-images.githubusercontent.com/26695327/155400872-5da6ef69-110b-4487-b958-f2132cb4b71d.png)
Putting the Dark Mode pack below won't fix it, Compliance will overwrite it except for font color.

**Comment by Pomi108** [comment]
This does not happen without the Dark Mode pack, meaning it is not our concern. The pack works fine on its own.
