### ISSUE TITLE
Cat bug

### ISSUE THREAD

**Issue by deepeshrao231** [Compliance-Resource-Pack/Compliance-Bedrock-32x#2]
Tamed Flat faced cat have mouth same as normal cat 
![Screenshot_20220403-214915_Minecraft](https://user-images.githubusercontent.com/102985124/161737905-4f0bec9d-ae7e-4c61-ae06-3ceeed5be68e.jpg)

**Comment by Pomi108** [comment]
The picture seems to be broken, can you reupload it?

**Comment by deepeshrao231** [comment]
> The picture seems to be broken, can you reupload it?

Re-upload done

**Comment by Juknum** [comment]
I'm not really into bedrock edition but is your game only using Compliance? It seems to be modded when I see the health bar, so it might be a compatibility issue, can you try with only Compliance?

**Comment by Pomi108** [comment]
This issue has already been fixed in the development pack
