### ISSUE TITLE
Water texture isn't updated

### ISSUE THREAD

**Issue by BigPhobos** [Compliance-Resource-Pack/Compliance-Bedrock-32x#4]
![image](https://user-images.githubusercontent.com/76231975/174513523-727cf626-a78f-4334-bb26-59492889e464.png)

**Comment by Pomi108** [comment]
Are you using beta 20 or the current WIP pack from the repo? What version and edition is this? Please provide more info.

**Comment by BigPhobos** [comment]
Bedrock Windows 10
32x
Beta 20

**Comment by Pomi108** [comment]
Beta 20 does not include the water texture because the pack was not complete at the time.
