### ISSUE TITLE
Every UI buttons in-game becomes corrupted.

### ISSUE THREAD

**Issue by aldwinmgn** [Compliance-Resource-Pack/Compliance-Bedrock-32x#5]
Some of the UI stuff looks janky and weird, also, most of them have lines cutting through as well as different colored glitches that needs to be addressed.

![Screenshot_2022-07-02-09-57-27-22_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/104106950/176983991-c18e4cea-751e-4e52-9cc8-e247266167c5.jpg)
![Screenshot_2022-07-02-09-57-30-76_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/104106950/176984003-75ea816d-a470-447f-b16a-956ac3f8f550.jpg)
![Screenshot_2022-07-02-09-58-00-91_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/104106950/176984013-9ad762ed-9208-4919-bdce-22abe16a1844.jpg)
![Screenshot_2022-07-02-09-57-41-92_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/104106950/176984018-1b772b47-7d52-489d-affd-27eba1e9c0cb.jpg)
![Screenshot_2022-07-02-09-57-30-76_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/104106950/176984020-7a473ca4-193c-4014-a6c8-466e4112cac2.jpg)
![Uploading Screenshot_2022-07-02-09-57-49-13_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

**Comment by Pomi108** [comment]
This should now be fixed and released on every platform (except curse, where the files still need to be approved.)
