### ISSUE TITLE
[Texture Correction] The Textures You Utilize Are Not the Correct Textures for the Nether Reactor Core Stages

### ISSUE THREAD

**Issue by DeadSkullzJr** [Compliance-Resource-Pack/Compliance-Bedrock-32x#6]
Hello developers of the current Faithful pack(s), I noticed you guys and gals used the Plastic based Nether Reactor Core stage textures as your primary base for your Bedrock port of the Faithful packs rather than the Vanilla textures the game is supposed to use, this isn't really your fault, but for some context. The Pocket Edition developers a few years back made a mistake when they introduced custom textures into game officially and swapped these reactor stage textures between the Vanilla and Plastic packs, they are well aware of the issue and have marked each report on the matter as "Won't Fix" in their bug reporting system, still doing so to this day. They may be refusing to fix it, but we can at least apply the corrections with our own resource packs.

Here are the original reactor stage textures that should be present.
https://mega.nz/file/xEJ32R7D#caFKkF_lfknZ5u8OwgqcMJ3zDnwuVbkrnshXKAPBt2E

This isn't all however, when the Nether Reactor was added to the game back in 2012, I noticed an inconsistency right away with one of the reactor core textures, the final stage texture to be exact. The final stage texture is uneven in the middle, it's supposed to be consistent with the previous stage textures by design. For some strange reason the developers never corrected this issue, whether or not anyone else has ever reported a "bug" about it I don't know, provided that I've been around Pocket Edition since it first came out on iOS, I've yet to really see anyone talk about it to this day (probably just not looking in the right places). I took it upon myself to correct this issue once and for all and spread it around a bit for those willing to make the proper corrections with their custom packs. Since Mojang never redid the original reactor textures for Bedrock Edition (v1.10+), you can utilize the textures and the fix I provided below for all forms of your Bedrock ported packs. You have my permission to utilize my fixed texture, otherwise the untouched original textures is provided with the link above.

Here is a comparison of the original final stage texture with my fixed texture:
<a href="https://imgur.com/g56QwRk"><img src="https://i.imgur.com/g56QwRk.png" title="source: imgur.com" /></a>

Download for the fixed texture:
https://mega.nz/file/gFYVXQZQ#sRM274Yr54corAYo7yvOBAecvCkuXaYCeFrd1Qk8LS0

**Comment by Pomi108** [comment]
This was a conscious decision. Since Vanilla uses the Plastic textures, and Mojang has refused to fix it, Faithful shall use them as well.
